name: first workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  # lint:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: 'master'
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.18'
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile --immutable
  #     - name: Run lint
  #       run: yarn lint
  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: 'master'
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.18'
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile --immutable
  #     - name: Build
  #       run: yarn build
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         path: dist
  # test:
  #   needs:
  #     - build
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: 'master'
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.18'
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile --immutable
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: dist
  #         path: dist
  #     - name: Test
  #       run: yarn test

  deploy:
    # needs:
    #   - test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.18'
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile --immutable
      # - name: Build
      #   run: yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Deploy with rsync
        run: rsync -avz ../../. ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/mnt/wpp_event_volume$
      # - name: Deploy to Staging server
      #   if: ${{ github.event_name == 'push' }}
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     ARGS: "-rlgoDzvc -i"
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: /mnt/wpp_event_volume
      #     # EXCLUDE: "/dist/, /node_modules/"
      #     SOURCE: '../../'
      #     SCRIPT_AFTER: |
      #       mv . ../../