name: first workflow

on:
  push:
    branches:
      - master

jobs:
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18'
      - name: Install dependencies
        run: yarn --offline --ignore-optional
      - name: Run lint
        run: yarn lint
